audit_header: false
title: Dr. Phillips-Windermere Real Estate Video Blog with Mark Ramey
description: Our mission at The Mark Ramey Group is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Mark Ramey Group, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Letters of the Heart
    url: /letters-of-the-heart/
client:
  name: Mark Ramey
  title:
  license_number:
  about_markdown: |
    • Among the top 1% of Real Estate Professiona;s in the Orlando Region<br>
    • Voted “Orlando Magazines – Hot 100 Realtor” for multiple years<br>
    • Recognized as a “5 Star – Customer Satisfaction” Professional for multiple years<br>
    • Member of the National Association of Realtors and a Member of the Orlando Regional Board of Realtor<br>
    • 20+ years of Finance and Real Estate experience with a team that specializes in Residential and Investment Real Estate sales and purchases.  Mark is an active, full time Realtor with a large center of influence in the greater Orlando area.  A consistent top performer, Mark and his team have received the following honors for multiple years; Top Listing Agent, Top Selling Agent, Most Closed Units and Highest closed Volume. <br>

    Born and raised in Chicago Illinois, I left the windy city and a career in auto sales and finance in 1998 when I moved to Orlando Florida.  It only took one glorious winter to realize that this was my new home.  I quickly started my new career as a Real Estate agent so that I could help others in their quest to live here in Winter Paradise.
  market: Dr. Phillips-Windermere
  brand: The Mark Ramey Group
  brokerage: Keller Williams Classic Realty
  address: 6900 Turkey Lake Rd. Orlando, FL 32819
  phone: 407-270-0011
  phone_type:
  phone2:
  phone2_type:
  email: Team@themarkrameygroup.com
  url: http://www.themarkrameygroup.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://markramey.boldleads.com/
  second_CTA_text: KW App
  second_CTA_URL: https://app.kw.com/KW1Q9P16Q/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you. Call or email me today at 407-270-0011 mark@themarkrameygroup.com"
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://markramey.boldleads.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Get FREE instant access to local homes from any mobile device."
    CTA_text2: "Keller Williams Realty Real Estate Search available on Android, iPhone, or iPad gives you access to more than 4 million homes."
    CTA_link_text2: "Download Now"
    CTA_url2: https://app.kw.com/KW1Q9P16Q/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheMarkRameyGroup
  linkedin_url: https://www.linkedin.com/in/themarkrameygroup/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCCGroJ6_uB7hvlIAvBStpHg?view_as=subscriber
  twitter_url: https://twitter.com/MarkRameyGroup
  instagram_url:
  pinterest_url: http://www.pinterest.com/MarkRameyGroup/
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
